"""make step_instances.step_id nullable for adhoc steps

Revision ID: 4643697c3984
Revises: 0003
Create Date: 2026-06-24 07:38:48.416485
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4643697c3984'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_instances', schema=None) as batch_op:
        batch_op.alter_column('step_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_instances', schema=None) as batch_op:
        batch_op.alter_column('step_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
