# Release Please does not run `uv lock`
# so after a release, uv.lock has old version number
# let's use this fix until this gets merged: 
# https://github.com/googleapis/release-please/pull/2693
name: Update lockfile

on:
  push:
    branches: [main]
    paths: [pyproject.toml]

permissions:
  contents: write

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: astral-sh/setup-uv@v5
      - run: uv lock
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update uv.lock"
